version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '0.0.0.0:3000:3000' # Allows access from any network interface
    env_file:
      - .env # Make sure your environment file is named .env
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_DATABASE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - mongo
      - redis
      - postgres

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
