# NodeJS Version 22.11.0
FROM node:22.11.0-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN pnpm install

# Set Env
ENV NODE_ENV development

EXPOSE 3000

# Cmd script
CMD ["pnpm", "run", "dev"]
