# NodeJS Version 22.11.0
FROM node:22.11.0-alpine

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN pnpm install

# Set Env
ENV NODE_ENV development

EXPOSE 3001

# Cmd script
CMD ["pnpm", "run", "dev"]
